export OUTPUT_FOLDER=/path/to/training_data
chimp extract_data patmosx 1983 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1984 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1985 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1986 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1987 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1988 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1989 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1990 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1991 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1992 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1993 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1994 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1995 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1996 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1997 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1998 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 1999 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 2000 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 8
chimp extract_data patmosx 2001 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 10
chimp extract_data patmosx 2002 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 10
chimp extract_data patmosx 2003 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 10
chimp extract_data patmosx 2004 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 10
chimp extract_data patmosx 2005 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 10
chimp extract_data patmosx 2006 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 10
chimp extract_data patmosx 2007 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 10
chimp extract_data patmosx 2008 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 10
chimp extract_data patmosx 2009 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 10
chimp extract_data patmosx 2010 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 8
chimp extract_data patmosx 2011 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 2012 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 2013 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 16
chimp extract_data patmosx 2014 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 16
chimp extract_data patmosx 2015 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 2016 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 16
chimp extract_data patmosx 2017 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 2018 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4

export OUTPUT_FOLDER=/path/to/test_data
chimp extract_data patmosx 2019 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 16
chimp extract_data patmosx 2020 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 16
chimp extract_data patmosx 2021 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 16
chimp extract_data patmosx 2022 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
chimp extract_data patmosx 2023 ? $OUTPUT_FOLDER --domain merra --time_step 1440 --n_processes 4
